name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test-lint:
    name: Build, Test & Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check compilation
        run: cargo check --workspace --all-targets

      - name: Run code formatter check
        run: cargo fmt --all --check

      - name: Run clippy lints
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Run workspace tests
        run: cargo test --workspace --lib
